EducacionAvanzada/EducacionAvanzada.WebAdmin/Controllers/GradoDetalleController.cs
using EducacionAvanzada.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EducacionAvanzada.WebAdmin.Controllers
{
    [Authorize]
    public class GradoDetalleController : Controller
    {
        ProfesorBL _profesorBL;
        GradosBL _gradoBL;
        JornadasBL _jornadaBL;
        seccionBL _seccionBL;

        public GradoDetalleController()
        {
            _profesorBL = new ProfesorBL();
            _gradoBL = new GradosBL();
            _jornadaBL = new JornadasBL();
            _seccionBL = new seccionBL();
             
        }
        // GET: GradoDetalle
        public ActionResult Index(int profesorId)
        {
            //probando por un error que se ocasiono
            try
            {
                var Profesor = _profesorBL.ObtenerProfesor(profesorId);
                Profesor.ListadeGradosPorProfesor = _gradoBL.ObtenerGradosPorProfesor(profesorId);
                ViewBag.profesorId = profesorId;
                ViewBag.nombreProfesor = Profesor.Nombre;
                return View(Profesor);
            }
            catch (Exception)
            {
                return RedirectToAction("Index", new { profesorId = profesorId });
            }

        }

        public ActionResult Crear(int profesorId)
        {
            var nuevoGradoDetalle = new GradoDetalle();
            nuevoGradoDetalle.ProfesorId = profesorId;

            var grados = _gradoBL.ObtenerGrados();
            var jornadas = _jornadaBL.ObtenerJornadas();
            var secciones = _seccionBL.ObtenerSecciones();

            var profesor = _profesorBL.ObtenerProfesorComoLista(profesorId);


            //ViewBag.notaId = notaId;

            //ViewBag.idalumno = alumnoId;


            ViewBag.GradoId = new SelectList(grados, "Id", "Descripcion");
            ViewBag.JornadaId = new SelectList(jornadas, "Id", "Descripcion");
            ViewBag.SeccionId = new SelectList(secciones, "Id", "Descripcion");

            ViewBag.ProfesorId = new SelectList(profesor, "Id", "Nombre");





            return View(nuevoGradoDetalle);
        }

        [HttpPost]
        public ActionResult Crear(GradoDetalle GradoDetalle)
        {
            var grados = _gradoBL.ObtenerGrados();
            var jornadas = _jornadaBL.ObtenerJornadas();
            var secciones = _seccionBL.ObtenerSecciones();
            var profesor = _profesorBL.ObtenerProfesorComoLista(GradoDetalle.ProfesorId);

            if (ModelState.IsValid)
            {

                if (GradoDetalle.GradoId == 0)
                {
                    ModelState.AddModelError("GradoId", "Seleccione un Grado");
                    ViewBag.GradoId = new SelectList(grados, "Id", "Descripcion");
                    ViewBag.JornadaId = new SelectList(jornadas, "Id", "Descripcion");
                    ViewBag.SeccionId = new SelectList(secciones, "Id", "Descripcion");
                    ViewBag.ProfesorId = new SelectList(profesor, "Id", "Nombre");
                    return View(GradoDetalle);
                }

                if (GradoDetalle.SeccionId == 0)
                {
                    ModelState.AddModelError("SeccionId", "Seleccione una Seccion");
                    ViewBag.GradoId = new SelectList(grados, "Id", "Descripcion");
                    ViewBag.JornadaId = new SelectList(jornadas, "Id", "Descripcion");
                    ViewBag.SeccionId = new SelectList(secciones, "Id", "Descripcion");
                    ViewBag.ProfesorId = new SelectList(profesor, "Id", "Nombre");
                    //ViewBag.idalumno = notasDetalle.AlumnoId;
                    return View(GradoDetalle);
                }

                if (GradoDetalle.JornadaId == 0)
                {
                    ModelState.AddModelError("JornadaId", "Seleccione una Jornada");
                    ViewBag.GradoId = new SelectList(grados, "Id", "Descripcion");
                    ViewBag.JornadaId = new SelectList(jornadas, "Id", "Descripcion");
                    ViewBag.SeccionId = new SelectList(secciones, "Id", "Descripcion");
                    ViewBag.ProfesorId = new SelectList(profesor, "Id", "Nombre");
                    return View(GradoDetalle);
                }

                _gradoBL.GuardarGradosDetalle(GradoDetalle);
                return RedirectToAction("Index", new { profesorId = GradoDetalle.ProfesorId});
            }

            ViewBag.GradoId = new SelectList(grados, "Id", "Descripcion");
            ViewBag.JornadaId = new SelectList(jornadas, "Id", "Descripcion");
            ViewBag.SeccionId = new SelectList(secciones, "Id", "Descripcion");
            ViewBag.ProfesorId = new SelectList(profesor, "Id", "Nombre");

            return View(GradoDetalle);
        }


        public ActionResult Editar(int id)
        {
            var gradoDetalle = _gradoBL.ObtenerGradoDetalle(id);

            var grados = _gradoBL.ObtenerGrados();
            var jornadas = _jornadaBL.ObtenerJornadas();
            var secciones = _seccionBL.ObtenerSecciones();
            var profesor = _profesorBL.ObtenerProfesorComoLista(gradoDetalle.ProfesorId);

            ViewBag.GradoId = new SelectList(grados, "Id", "Descripcion");
            ViewBag.JornadaId = new SelectList(jornadas, "Id", "Descripcion");
            ViewBag.SeccionId = new SelectList(secciones, "Id", "Descripcion");
            ViewBag.ProfesorId = new SelectList(profesor, "Id", "Nombre");


            return View(gradoDetalle);
        }

        [HttpPost]
        public ActionResult Editar(GradoDetalle gradoDetalle)
        {
            _gradoBL.GuardarGradosDetalle(gradoDetalle);

            return RedirectToAction("Index", new { profesorId = gradoDetalle.ProfesorId });
        }

        public ActionResult Eliminar(int id)
        {
            var gradoDetalle = _gradoBL.ObtenerGradoDetalle(id);

            return View(gradoDetalle);
        }

        [HttpPost]
        public ActionResult Eliminar(GradoDetalle gradoDetalle)
        {
            var profesor = gradoDetalle.ProfesorId;

            _gradoBL.EliminarGradoDetalle(gradoDetalle.Id);

            return RedirectToAction("Index", new { profesorId = profesor });
        }
    }
}

EducacionAvanzada/EducacionAvanzada.WebAdmin/Controllers/MateriaDetalleController.cs
using EducacionAvanzada.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EducacionAvanzada.WebAdmin.Controllers
{
    [Authorize]
    public class MateriaDetalleController : Controller
    { 
        GradosBL _gradoBL;
        materiaBL _materiaBL;

        public MateriaDetalleController()
        {
            _gradoBL = new GradosBL();
            _materiaBL = new materiaBL();
        }

        // GET: MateriaDetalle
        public ActionResult Index(int gradoDetalleId)
        {
            var GradoDetalle = _gradoBL.ObtenerGradoDetalle(gradoDetalleId);
            GradoDetalle.ListadeMateriasPorGradoyProfesor = _materiaBL.ObtenerMateriasPorGradoyProfesor(gradoDetalleId);
           
            ViewBag.gradoDetalleId = gradoDetalleId;

            return View(GradoDetalle);
        }

        public ActionResult Crear(int gradoDetalleId)
        {
            var nuevamateriaDetalle = new MateriaDetalle();
            nuevamateriaDetalle.GradoDetalleId = gradoDetalleId;

            var materias = _materiaBL.Obtenermaterias();
            
            

            //ViewBag.idalumno = alumnoId;


            ViewBag.MateriaId = new SelectList(materias, "Id", "Descripcion");
            

            return View(nuevamateriaDetalle);
        }

        [HttpPost]
        public ActionResult Crear(MateriaDetalle materiaDetalle)
        {
            var materias = _materiaBL.Obtenermaterias();

            if (ModelState.IsValid)
            {

                if (materiaDetalle.MateriaId == 0)
                {
                    ModelState.AddModelError("MateriaId", "Seleccione una Materia");
                    ViewBag.MateriaId = new SelectList(materias, "Id", "Descripcion");
                    return View(materiaDetalle);
                }

               _materiaBL.GuardarMateriaDetalle(materiaDetalle);
                return RedirectToAction("Index", new { gradoDetalleId = materiaDetalle.GradoDetalleId });
            }

            ViewBag.MateriaId = new SelectList(materias, "Id", "Descripcion");

            return View(materiaDetalle);
        }

        public ActionResult Editar(int id)
        {
            var materiaDetalle = _materiaBL.ObtenerMateriaDetalle(id);

            var materias = _materiaBL.Obtenermaterias();
            

            ViewBag.MateriaId = new SelectList(materias, "Id", "Descripcion");
            

            return View(materiaDetalle);
        }

        [HttpPost]
        public ActionResult Editar(MateriaDetalle materiaDetalle)
        {
            _materiaBL.GuardarMateriaDetalle(materiaDetalle);

            return RedirectToAction("Index", new { gradoDetalleId = materiaDetalle.GradoDetalleId});
        }

        public ActionResult Eliminar(int id)
        {
            var materiaDetalle = _materiaBL.ObtenerMateriaDetalle(id);

            return View(materiaDetalle);
        }

        [HttpPost]
        public ActionResult Eliminar(MateriaDetalle materiaDetalle)
        {
            var gradoDetalle = materiaDetalle.GradoDetalleId;

            _materiaBL.EliminarMateriaDetalle(materiaDetalle.Id);

            return RedirectToAction("Index", new { gradoDetalleId = gradoDetalle });
        }

    }
}

EducacionAvanzada/EducacionAvanzada.WebAdmin/Controllers/ProfesoresController.cs
using EducacionAvanzada.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EducacionAvanzada.WebAdmin.Controllers
{
    [Authorize]
    public class ProfesoresController : Controller
    {
        ProfesorBL _profesorBL;
        public ProfesoresController()
        {
            _profesorBL = new ProfesorBL();
        }

        // GET: Profesores
        public ActionResult Index()
        {
            var listadeProfesores = _profesorBL.ObtenerProfesores();
            return View(listadeProfesores);
        }

        public ActionResult Crear()
        {
            var nuevoProfesor = new Profesor();

            return View(nuevoProfesor);
        }

        [HttpPost]
        public ActionResult Crear(Profesor profesor)
        {
            if (ModelState.IsValid)
            {
                if (profesor.Nombre != profesor.Nombre.Trim())
                {
                    ModelState.AddModelError("Nombre", "No debe de haber espacios al inicio o al final");
                    return View(profesor);
                }
                profesor.Contrasena = Encriptar.CodificarContrasena(profesor.Contrasena);
                _profesorBL.GuardarProfesor(profesor);

                return RedirectToAction("Index");
            }

            return View(profesor);
        }

        public ActionResult Editar(int id)
        {
            var profesor = _profesorBL.ObtenerProfesor(id);


            return View(profesor);
        }

        [HttpPost]
        public ActionResult Editar(Profesor profesor)
        {
            _profesorBL.GuardarProfesor(profesor);

            return RedirectToAction("Index");
        }


    }
}

EducacionAvanzada/EducacionAvanzada.WebAdmin/Views/GradoDetalle/Crear.cshtml
@model EducacionAvanzada.BL.GradoDetalle

@{
    ViewBag.Title = "Crear";
}

<h2>Asignar Grado a Profesor</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Profesor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProfesorId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Profesor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GradoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Grado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.seccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SeccionId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.seccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Jornada, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("JornadaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Jornada, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Anio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Anio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Anio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a Grados Impartidos", "Index", "GradoDetalle", new { profesorId = Model.ProfesorId}, null)
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

EducacionAvanzada/EducacionAvanzada.WebAdmin/Views/GradoDetalle/Editar.cshtml
@model EducacionAvanzada.BL.GradoDetalle

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Profesor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProfesorId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Profesor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GradoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Grado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.seccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SeccionId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.seccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Jornada, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("JornadaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Jornada, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Anio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Anio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Anio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a Grados Impartidos", "Index", "GradoDetalle", new { profesorId = Model.ProfesorId }, null)
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

EducacionAvanzada/EducacionAvanzada.WebAdmin/Views/GradoDetalle/Eliminar.cshtml
@model EducacionAvanzada.BL.GradoDetalle

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>

<h3>¿Estás Seguro que Quieres Eliminar este Registro?</h3>
<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Profesor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Profesor.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grado.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.seccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.seccion.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Jornada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Jornada.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Anio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Anio)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(model => model.ProfesorId)
        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            @Html.ActionLink("Regresar a Grados Impartidos", "Index", "GradoDetalle", new { profesorId = Model.ProfesorId}, null)
        </div>
    }
</div>

EducacionAvanzada/EducacionAvanzada.WebAdmin/Views/GradoDetalle/Index.cshtml
@model EducacionAvanzada.BL.Profesor

@{
    ViewBag.Title = "Index";
}

<h2>Grados Impartidos por Profesor </h2>
<h3>@ViewBag.nombreProfesor</h3>
<p>
    @Html.ActionLink("Nuevo Grado", "Crear", "GradoDetalle", new { profesorId = ViewBag.profesorId }, null)
</p>
<table class="table">
    <tr>
        <th>
            Profesor
        </th>
        <th>
            Grado
        </th>
        <th>
            Seccion
        </th>
        <th>
            Jornada
        </th>
        <th>
            Año
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.ListadeGradosPorProfesor) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Profesor.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Grado.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.seccion.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Jornada.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Anio)
        </td>

        <td>
            @Html.ActionLink("Editar", "Editar", new { id=item.Id }, null) |
            @Html.ActionLink("Eliminar", "Eliminar", new { id=item.Id }) |
            @Html.ActionLink("Ver Materias", "Index", "MateriaDetalle", new { gradoDetalleId = item.Id }, null)
        </td>
    </tr>
    
}
   

</table>
@Html.ActionLink("Regresar a Lista de Profesores", "Index", "Profesores")